development: &default
  adapter: postgresql
  database: ionic_dev
  username: postgres
  host: localhost
  encoding: utf8
  reconnect: true

test:
  <<: *default
  database: ionic_test

staging:
  <<: *default

production:
  <<: *default
